# Generated by Django 5.0.6 on 2024-06-12 10:11

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[accounts.validators.validate_phone_number], verbose_name='Phone number'),
        ),
    ]
