# Generated by Django 5.0.6 on 2024-06-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_boardgame_max_game_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardgame',
            options={'ordering': ['name']},
        ),
    ]
